# Generated by Django 4.2.2 on 2024-04-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
