# Generated by Django 4.2.2 on 2024-04-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличные'), ('transfer', 'перевод')], max_length=10, verbose_name='способ оплаты'),
        ),
    ]
