# Generated by Django 4.2.2 on 2024-05-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
    ]
